### PR TITLE
quote route parameters

### LINKED ISSUE #14: Creates malformed type if route param contains a dash
it created this route, for instance:

```
{ route: "/countries/[encoded-country]", params: { encoded-country: string | number }, query?: Query }
```

The created type ought to have quotes to avoid this (~and i guess if a route has quotes in it, it should probably escape the quotes too~ looks like quotes are not allowed in query parameters at all so that's fine)

### PR DESCRIPTION
**Pull request by osdiab**
Closes #14 

Ensures that it always produces valid typescript even if hyphens are in the path name.

### CODE REVIEW

**Comment by ckastbjerg** [comment]
Hmm, not sure how to best resolve this one. A bit to sketchy in the Github webeditor. 
I don't have experience with merging from forks. Should I do something or should you? :)

...and this snapshot test will quickly become a pain I see 🤦

**Comment by ckastbjerg** [comment]
Also, I'll bump the patch version once this is merged and I have tested a bit on my own project. Still doing releases by hand here ;)

**Comment by osdiab** [comment]
I think this is easiest:

1. Open terminal, check out this branch
2. merge main into this branch
3. there will be conflicts on that snapshot file - just rerun `yarn test` to regenerate the snapshot
4. make sure the snapshot makes sense
5. `git commit`, to complete the merge commit
6. push that, and you should be good to merge this into main

**Comment by osdiab** [comment]
i just did the merge, so should be good now - the snapshot diff looked like this:

Screen Shot 2021-11-12 at 10 10 38

**Comment by ckastbjerg** [comment]
Thanks for fixing it :)

> I think this is easiest:
> 
> 1. Open terminal, check out this branch
> 2. merge main into this branch
> 3. there will be conflicts on that snapshot file - just rerun `yarn test` to regenerate the snapshot
> 4. make sure the snapshot makes sense
> 5. `git commit`, to complete the merge commit
> 6. push that, and you should be good to merge this into main

Thanks for taking the time to explain! But I do know how to resolve conflicts. The thing was, that I couldn't checkout this branch (`osdiab:osdiab/quote-and-escape-routes`) as it comes from your fork. Guess I would need access to your fork and resolve them there or have you do it as you did :9

**Comment by osdiab** [comment]
Ah I figured there was some way for you to check it out since when I make the PRs it has a checkbox to allow edits from maintainers - lol maybe there is but idk. As more stuff comes up I'll try to deal with conflicts like that when they come :)

**Pull request merged**
